### PR TITLE
Add tracking

### PR DESCRIPTION
**Pull request by clementbiron**
That changeset:
- add Matomo tracking code
- update Matomo opt-out code

### CODE REVIEW

**Review by MattiSG — APPROVED** [review]
LGTM! The visual integration is perfect 🙂 
How do you intend to check if this works well?

**Comment by clementbiron** [comment]
>  How do you intend to check if this works well?

I didn't think about how to test because I didn't think that this third party code might not work. Excess of confidence!

**Comment by MattiSG** [comment]
I just mean: shall we check tomorrow if stats are actually stored? 😉

**Comment by clementbiron** [comment]
Yes of course!

**Pull request merged**
