### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by clementbiron**
That PR update `circleci/hugo` from `0.3.1` to `1.3.0`, `gh-pages` from `^1.0.0` to `^4.0.0` and specify the minimum node version needed.

I haven't found a way other than to disable `html-proofer` for this to work. I will need help to find how to fix the following error shown in CicleCI.  

```console
#!/bin/bash -eo pipefail
htmlproofer ./public \
   \
   --allow-hash-href  \
   \
  --alt-ignore  \
   \
  --checks-to-ignore '' \
   \
   \
   --check-html  \
   \
   \
   \
  --directory-index-file index.html \
   --disable-external  \
   --empty-alt-ignore  \
  --error-sort ''  \
   \
  --extension '.html' \
   \
  --file-ignore '' \
  --http-status-ignore '' \
  --internal-domains '' \
   \
   \
   \
   \
   \
   \
  --log-level info \
   \
  --storage-dir 'tmp/.htmlproofer' \
  --timeframe '1h' \
  --typhoeus-config '{}' \
  --url-ignore '' \
  --url-swap ''

htmlproofer 4.4.3 | Error:  Whoops, we can't understand your command.
htmlproofer 4.4.3 | Error:  invalid option: --checks-to-ignore
Did you mean?  check-internal-hash
htmlproofer 4.4.3 | Error:  Run your command again with the --help switch to see available options.
/var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': invalid option: --checks-to-ignore (OptionParser::InvalidOption)
Did you mean?  check-internal-hash
	from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /var/lib/gems/3.0.0/gems/html-proofer-4.4.3/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/bin/htmlproofer:25:in `load'
	from /usr/local/bin/htmlproofer:25:in `<main>'

Exited with code exit status 1
CircleCI received exit code 1
```

### CODE REVIEW

**Comment by MattiSG** [comment]
Thanks, looks promising!

`htmlproofer` is used to validate the HTML output. It is an important failsafe mechanism. It seems that the CircleCI orb has some issues (cf. https://github.com/CircleCI-Public/hugo-orb/issues/51), and we currently rely on it to execute `htmlproofer`.

I see the following options:

1. We stop relying on the orb and install and execute `htmlproofer` ourselves ([example](https://github.com/MattiSG/jekyll-template/blob/main/.circleci/config.yml#L50-L52)).
2. We play with options to pass to the orb until we find something that works. I looked at the [documentation](https://circleci.com/developer/orbs/orb/circleci/hugo#commands-html-proofer) and at the [`htmlproofer` changelog](https://github.com/gjtorikian/html-proofer/releases) and open issues and did not find anything related to `invalid option: --checks-to-ignore`, except that this option is not listed on the [README](https://github.com/gjtorikian/html-proofer/releases), so it might have been removed at some point and the orb is not up to date.
3. We open a PR to the orb removing this option, and potentially publish our fork of the orb and use it until this is fixed if merging takes too long.

In any case, I believe we should open an issue in the [orb repository](https://github.com/CircleCI-Public/hugo-orb/issues/).

**Comment by clementbiron** [comment]
Issue opened https://github.com/CircleCI-Public/hugo-orb/issues/57 👍

**Comment by clementbiron** [comment]
Thanks Matti for your review.

I chose the first option by installing and running `htmlproofer` on our own.

`htmlproofer` is reporting 59 failures which I suppose will have to be dealt with in another PR.

**Comment by MattiSG** [comment]
I fixed the issue related to htmlproofer by pinning its version and updating the CLI syntax, as documented in https://github.com/CircleCI-Public/hugo-orb/issues/57#issuecomment-1333787381.

I corrected the issues detected by htmlproofer, including a very problematic one that was introduced in https://github.com/openfisca/openfisca.org/pull/95 where we had inadvertently broken the main CTA links on the homepage 😓 In some way, it was useful that the build broke then.

**Review by MattiSG — APPROVED** [review]
🚀

**Pull request merged**
